version: "3"

services:
  squid:
    image: pmithil7/squid:v1
    ports:
      - "3128:3128"
    restart: unless-stopped
    container_name: squid
    volumes:
      - /srv/docker/squid/cache:/var/spool/squid
      - /home/mapatel/squid.conf:/etc/squid/squid.conf
